name: "Print details when an issue is opened on Github"
on:
  issues:
    types: opened
jobs:
  printIssueDetails:
    runs-on: ubuntu-latest
    steps:
      - name: "Print all details"
        env:
          JOB_CONTEXT: ${{ toJson(github) }}
        run: echo "$JOB_CONTEXT"